
# ====================NGINX-WITH-SINGLE-VOLUME-AS-CONFIGMAPS====================
# git clone https://github.com/mavrick202/dockertest1.git
# cd dockertest1
# ku create configmap html1 --from-file=index.html
# ku create configmap js1 --from-file=scorekeeper.js
# ku create configmap css1 --from-file=style.css

# ===================-NGINX-MAP-MULTIPLE-CONFIGMAPS-TO-SINGLE-FOLDER-===========     


---

apiVersion: v1
data:
  env: prod
  owner: sree
  sleep-interval: "25"
  awsregion: 'us-east-1'
kind: ConfigMap
metadata:
  name: testconfig2

---

apiVersion: v1
kind: Pod
metadata:
  name: testpod001
spec:
  containers:
    - name: testpod001
      image: sreeharshav/utils:latest
      env:
        - name: MUNNA_BHAI_MBBS_1
          valueFrom:
            configMapKeyRef:
              name: testconfig2
              key: env
        - name: MUNNA_BHAI_MBBS_2
          valueFrom:
            configMapKeyRef:
              name: testconfig2
              key: owner
        - name: MUNNA_BHAI_MBBS_2
          valueFrom:
            configMapKeyRef:
              name: testconfig2
              key: awsregion      

