# echo -n AABBCCCDDDACCESSKEY | base64
# #echo -n AABBCCCDDDSECRETKEY | base64

apiVersion: v1
kind: Secret
metadata:
  name: aws-access-keys
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQVFFTUlKQllGNVNSWVhaSUgK
  AWS_SECRET_ACCESS_KEY: RUh5MTkzTjBoV2oxMmxqaFduZFBoeW0xU1E1SVp2ZEtaL002U1hBRw==


---
# kubectl create configmap awsregion --from-literal=AWS_DEFAULT_REGION='us-east-1'


apiVersion: apps/v1
kind: Deployment
metadata:
  name: awscli-deployment
  labels:
    app: awscli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awscli
  template:
    metadata:
      labels:
        app: awscli
    spec:
      containers:
        - name: awscli
          image: banst/awscli
          #command: ["s3 ls"] #ENTRYPOINT in Dockerfile
          args: ["ec2", "describe-instances"]  #CMD in Dockerfile
          ports:
            - containerPort: 3306
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-access-keys
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-access-keys
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              valueFrom:
                configMapKeyRef:
                  name: awsregion
                  key: AWS_DEFAULT_REGION

