apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy01-prod
  labels:
    app: deploy01
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deploy01
  template:
    metadata:
      labels:
        app: deploy01
    spec:
      containers:
      - name: deploy01
        image: sreeharshav/rollingupdate:v5
        ports:
        - containerPort: 80
      nodeSelector:
        env: prod

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy01-nolabel
  labels:
    app: deploy01
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deploy01
  template:
    metadata:
      labels:
        app: deploy01
    spec:
      containers:
      - name: deploy01
        image: sreeharshav/rollingupdate:v5
        ports:
        - containerPort: 80



---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy01-taints
  labels:
    app: deploy01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy01
  template:
    metadata:
      labels:
        app: deploy01
    spec:
      containers:
      - name: deploy01
        image: sreeharshav/rollingupdate:v5
        ports:
        - containerPort: 80
      tolerations:
       - key: "env"
         operator: "Equal"
         value: "temple"
         effect: "NoSchedule"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy01-taints
  labels:
    app: deploy01
spec:
  replicas: 4
  selector:
    matchLabels:
      app: deploy01
  template:
    metadata:
      labels:
        app: deploy01
    spec:
      containers:
      - name: deploy01
        image: sreeharshav/rollingupdate:v5
        ports:
        - containerPort: 80
      tolerations:
       - key: "env"
         operator: "Equal"
         value: "factory"
         effect: "NoSchedule"
       - key: "env"
         operator: "Equal"
         value: "madhuloka"
         effect: "NoSchedule"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy01-taints-noexecute
  labels:
    app: deploy01
spec:
  replicas: 4
  selector:
    matchLabels:
      app: deploy01
  template:
    metadata:
      labels:
        app: deploy01
    spec:
      containers:
      - name: deploy01
        image: sreeharshav/rollingupdate:v5
        ports:
        - containerPort: 80
      tolerations:
       - key: "env"
         operator: "Equal"
         value: "factory"
         effect: "NoExecute"
       - key: "env"
         operator: "Equal"
         value: "madhuloka"
         effect: "NoExecute"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy01-key-exists
  labels:
    app: deploy01
spec:
  replicas: 4
  selector:
    matchLabels:
      app: deploy01
  template:
    metadata:
      labels:
        app: deploy01
    spec:
      containers:
      - name: deploy01
        image: sreeharshav/rollingupdate:v5
        ports:
        - containerPort: 80
      tolerations:
       - key: "env"
         operator: "Exists"
         effect: "NoSchedule"

